-- run this once in the supabase sql editor

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null default 'a guy',
  score integer not null check (score >= 0),
  distance integer not null default 0 check (distance >= 0),
  overtakes integer not null default 0 check (overtakes >= 0),
  best_speed integer not null default 0 check (best_speed >= 0),
  mode text not null default 'normal' check (mode in ('normal', 'bomb')),
  created_at timestamptz not null default now()
);

create index if not exists scores_score_idx
  on public.scores (score desc);

create index if not exists scores_created_at_idx
  on public.scores (created_at desc);

create table if not exists public.flag_quiz_scores (
  id bigint generated by default as identity primary key,
  name text not null default 'a guy',
  score integer not null check (score >= 0),
  total integer not null check (total > 0),
  percentage integer not null check (percentage between 0 and 100),
  created_at timestamptz not null default now()
);

create index if not exists flag_quiz_scores_rank_idx
  on public.flag_quiz_scores (percentage desc, score desc, created_at asc);

alter table public.scores enable row level security;
alter table public.flag_quiz_scores enable row level security;

-- public leaderboard reads
drop policy if exists "scores are publicly readable" on public.scores;
create policy "scores are publicly readable"
on public.scores
for select
to anon, authenticated
using (true);

-- public score submission
drop policy if exists "scores are publicly insertable" on public.scores;
create policy "scores are publicly insertable"
on public.scores
for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 16
  and score >= 0
  and distance >= 0
  and overtakes >= 0
  and best_speed >= 0
  and mode in ('normal', 'bomb')
);

-- public flag quiz leaderboard reads
drop policy if exists "flag quiz scores are publicly readable" on public.flag_quiz_scores;
create policy "flag quiz scores are publicly readable"
on public.flag_quiz_scores
for select
to anon, authenticated
using (true);

-- public flag quiz score submission
drop policy if exists "flag quiz scores are publicly insertable" on public.flag_quiz_scores;
create policy "flag quiz scores are publicly insertable"
on public.flag_quiz_scores
for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 30
  and score between 0 and total
  and total > 0
  and percentage between 0 and 100
);

-- no update/delete policy on purpose.
-- players can submit scores and read the leaderboard,
-- but the browser cannot edit or delete existing scores.
