-- run this once in the supabase sql editor

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null default 'a guy',
  score integer not null check (score >= 0),
  distance integer not null default 0 check (distance >= 0),
  overtakes integer not null default 0 check (overtakes >= 0),
  best_speed integer not null default 0 check (best_speed >= 0),
  mode text not null default 'normal' check (mode in ('normal', 'bomb')),
  created_at timestamptz not null default now()
);

create index if not exists scores_score_idx
  on public.scores (score desc);

create index if not exists scores_created_at_idx
  on public.scores (created_at desc);

alter table public.scores enable row level security;

-- public leaderboard reads
drop policy if exists "scores are publicly readable" on public.scores;
create policy "scores are publicly readable"
on public.scores
for select
to anon, authenticated
using (true);

-- public score submission
drop policy if exists "scores are publicly insertable" on public.scores;
create policy "scores are publicly insertable"
on public.scores
for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 16
  and score >= 0
  and distance >= 0
  and overtakes >= 0
  and best_speed >= 0
  and mode in ('normal', 'bomb')
);

-- no update/delete policy on purpose.
-- players can submit scores and read the leaderboard,
-- but the browser cannot edit or delete existing scores.
